version: '2.1'

services:
  mysql:
    image: bitnami/mariadb:10.5.9
    ports:
      - '3306:3306'
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
      - './sql:/docker-entrypoint-initdb.d'
      - './my.cnf:/opt/bitnami/mariadb/conf/my_custom.cnf'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_ROOT_PASSWORD=Mysql1!.
      - MARIADB_USER=nbia_user
      - MARIADB_PASSWORD=nbia_password
      - MARIADB_DATABASE=nbiadb
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
  tomcat:
    image: jrutecht/bitnami-tomcat9-jdk18:latest
    volumes:
      - './webapps/nlst.war:/opt/bitnami/tomcat/webapps_default/nlst.war'
      - './tomcatfiles/conf/context.xml:/opt/bitnami/tomcat/conf/context.xml'
      - './tomcatfiles/conf/server.xml:/opt/bitnami/tomcat/conf/server.xml'
      - './tomcatfiles/conf/jaas.config:/opt/bitnami/tomcat/conf/jaas.config'
      - './tomcatfiles/lib/mysql-connector-java-5.1.34.jar:/opt/bitnami/tomcat/lib/mysql-connector-java-5.1.34.jar'
      - './tomcatfiles/lib/nbia.properties:/opt/bitnami/tomcat/lib/nbia.properties'
      - './dicoms:/opt/dicoms'
    ports:
      - '24080:24080'
      - '8080:8080'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - TOMCAT_ALLOW_REMOTE_MANAGEMENT=yes
      - TOMCAT_USERNAME=admin
      - TOMCAT_PASSWORD=admin
      - TOMCAT_EXTRA_JAVA_OPTS=-Djava.security.auth.login.config=/opt/bitnami/tomcat/conf/jaas.config -Dlog4j.configuration=/opt/bitnami/tomcat/lib/log4j.properties
volumes:
  mariadb_data:
    driver: local