version: '2.1'

services:
  mysql:
    image: bitnami/mariadb:10.5.9
    volumes:
      - mariadb_data:/bitnami/mariadb
      - ./sql:/docker-entrypoint-initdb.d
      - ./my.cnf:/opt/bitnami/mariadb/conf/my_custom.cnf
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_ROOT_PASSWORD=Mysql1!.
      - MARIADB_USER=nbia_user
      - MARIADB_PASSWORD=nbia_password
      - MARIADB_DATABASE=nbiadb
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
    logging:
      options:
        max-size: 5m
  tomcat:
    image: tomcat:9-jdk8
    volumes:
      - ./webapps/nbia-api.war:/usr/local/tomcat/webapps/nbia-api.war
      - ./webapps/nbia-download.war:/usr/local/tomcat/webapps/nbia-download.war
      - ./conf/context.xml:/usr/local/tomcat/conf/context.xml
      - ./conf/server.xml:/usr/local/tomcat/conf/server.xml
      - ./conf/jaas.config:/usr/local/tomcat/conf/jaas.config
      - ./lib/nbia.properties:/usr/local/tomcat/lib/nbia.properties
      - ./lib/mysql-connector-java-5.1.34.jar:/usr/local/tomcat/lib/mysql-connector-java-5.1.34.jar
      - ./lib/UIDNames.properties:/usr/local/tomcat/lib/UIDNames.properties
      - ./lib/userAgreement.txt:/usr/local/tomcat/lib/userAgreement.txt
      - ./lib:/usr/local/tomcat/lib/custom
      - ./dicoms:/opt/dicoms
    environment:
      - CATALINA_OPTS=-Djava.security.auth.login.config=/usr/local/tomcat/conf/jaas.config -Dlog4j.configuration=/usr/local/tomcat/lib/log4j.properties
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/nbia-api/up"]
      interval: 1m
      timeout: 5s
      retries: 3
    logging:
      options:
        max-size: 5m
  solr:
    image: docker.io/bitnami/solr:8
    environment:
      - SOLR_ENABLE_AUTHENTICATION=no
      - SOLR_CORE_CONF_DIR=/opt/solr_conf
      - SOLR_CORES=nbia
    volumes:
      - ./solr:/opt/solr_conf
    logging:
      options:
        max-size: 5m
  web:
    image: docker.io/nginx:latest
    volumes:
      - ./html:/var/www/html
      - ./nbia.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
    logging:
      options:
        max-size: 5m
volumes:
  mariadb_data:
    driver: local
